version: '3.8'

services:
  db:
    image: postgres:16
    secrets:
      - db-password
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      update_config:
        order: start-first
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - uschedule-net

  backend:
    image: ghcr.io/arsen2019/uschedule:${GIT_COMMIT_HASH:-latest}
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - uschedule-net
      - traefik-net

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.schedule.arsgreg.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"


networks:
  uschedule-net:
    external: true
  traefik-net:
    external: true

volumes:
  postgres-data:
secrets:
  db-password:
    external: true

