version: '3.8'

services:
  db:
    image: postgres:16
    container_name: uschedule-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - uschedule-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      dockerfile: Dockerfile
      args:
        DB_PASSWORD_FILE: ${DB_PASSWORD}
    container_name: uschedule-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DB_URL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - uschedule-net
      - traefik

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.schedule.arsgreg.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"




networks:
  traefik:
    external: true
  uschedule-net:
    name: uschedule-net
    driver: bridge
volumes:
  postgres-data:
